apiVersion: vista.fortiminds.io/v1
businessApplication:
  criticality: Tier2
  id: 9b2235f4-191a-4558-ba21-eb3058b9b5f7
  name: test_fm_vists_005
governance:
  enforced: true
  policies:
    - VISTA-CONTEXT-001
kind: RepositoryManifest
metadata:
  organisation: testveracode
  repository: test_005
scanners:
  - enabled: true
    name: veracode
    profile: test_fm_vists_005
